# Generated by Django 2.1.2 on 2019-03-09 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginrecord',
            options={'verbose_name_plural': '用户登陆记录'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': '项目信息'},
        ),
    ]
