# Generated by Django 2.1.2 on 2019-03-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190304_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
