# Generated by Django 2.1.2 on 2019-03-25 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_webmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiname', models.CharField(max_length=20, null=True, verbose_name='后端测试名称')),
                ('apides', models.CharField(max_length=50, null=True, verbose_name='后端测试描述')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name_plural': '后端测试管理',
            },
        ),
    ]
