# Generated by Django 2.1.2 on 2019-03-25 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_apimanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimanager',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='webmanager',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Project', verbose_name='所属项目'),
        ),
    ]
