# Generated by Django 2.1.2 on 2019-03-26 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190325_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiname', models.CharField(max_length=100, null=True, verbose_name='接口名称')),
                ('apimethod', models.CharField(choices=[('get', 'get'), ('post', 'post'), ('put', 'put'), ('delete', 'delete'), ('patch', 'patch')], default='get', max_length=200, null=True, verbose_name='请求方法')),
                ('apiurl', models.CharField(max_length=200, null=True, verbose_name='url地址')),
                ('apiparam', models.TextField(blank='None', max_length=800, null=True, verbose_name='请求参数param')),
                ('apijson', models.TextField(blank='None', max_length=800, null=True, verbose_name='请求数据json')),
                ('apiresponse', models.TextField(max_length=5000, null=True, verbose_name='响应数据json')),
                ('apistatus', models.BooleanField(default=True, verbose_name='是否通过')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('apiManager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ApiManager')),
            ],
        ),
    ]
