# Generated by Django 2.1.2 on 2019-03-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_apicase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apicase',
            options={'verbose_name_plural': '后端测试案例'},
        ),
        migrations.AddField(
            model_name='apicase',
            name='index',
            field=models.IntegerField(default=1, verbose_name='测试序号'),
        ),
        migrations.AddField(
            model_name='apicase',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='apimanager',
            name='apiurl',
            field=models.CharField(max_length=200, null=True, verbose_name='url地址'),
        ),
        migrations.AlterField(
            model_name='project',
            name='prodes',
            field=models.CharField(max_length=50, verbose_name='项目描述'),
        ),
        migrations.AlterField(
            model_name='project',
            name='proname',
            field=models.CharField(max_length=20, verbose_name='项目'),
        ),
    ]
