# Generated by Django 2.1.2 on 2019-03-28 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20190328_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webname', models.CharField(max_length=100, verbose_name='步骤名称')),
                ('webcss', models.TextField(max_length=800, verbose_name='Css选择器')),
                ('weboprate', models.TextField(blank='None', max_length=800, null=True, verbose_name='元素操作')),
                ('webresponse', models.TextField(max_length=5000, null=True, verbose_name='验证数据')),
                ('apistatus', models.BooleanField(default=True, verbose_name='是否通过')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('index', models.IntegerField(default=1, verbose_name='测试序号')),
                ('webManager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.WebManager')),
            ],
            options={
                'verbose_name_plural': '前端测试案例',
            },
        ),
    ]
