# Generated by Django 2.1.2 on 2019-03-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_webcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcase',
            name='webcss',
            field=models.TextField(max_length=800, null=True, verbose_name='Css选择器'),
        ),
        migrations.AlterField(
            model_name='webcase',
            name='webname',
            field=models.CharField(max_length=100, null=True, verbose_name='步骤名称'),
        ),
    ]
