# Generated by Django 2.1.2 on 2019-03-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20190328_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webcase',
            options={'ordering': ('index',), 'verbose_name_plural': '前端测试案例'},
        ),
        migrations.RemoveField(
            model_name='webcase',
            name='apistatus',
        ),
        migrations.RemoveField(
            model_name='webcase',
            name='webresponse',
        ),
        migrations.AddField(
            model_name='webcase',
            name='webparam',
            field=models.TextField(max_length=500, null=True, verbose_name='操作参数'),
        ),
    ]
