# Generated by Django 2.1.2 on 2019-03-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_webmanager_apiurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webmanager',
            old_name='apiurl',
            new_name='weburl',
        ),
    ]
