# Generated by Django 2.1.2 on 2019-03-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_webmanager_oprateobj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webmanager',
            name='oprateOBj',
        ),
        migrations.AddField(
            model_name='webcase',
            name='oprateOBj',
            field=models.CharField(max_length=200, null=True, verbose_name='操作类型'),
        ),
    ]
