# Generated by Django 2.1.2 on 2019-03-31 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20190328_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimanager',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Project', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='webmanager',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Project', verbose_name='所属项目'),
        ),
    ]
