# Generated by Django 2.1.2 on 2019-03-31 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0019_auto_20190331_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicase',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webcase',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apicase',
            name='apiManager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ApiManager', verbose_name='前端模块'),
        ),
        migrations.AlterField(
            model_name='webcase',
            name='webManager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.WebManager', verbose_name='前端模块'),
        ),
    ]
