# Generated by Django 2.1.2 on 2019-04-01 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0022_testtype_typename'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtype',
            name='index',
            field=models.IntegerField(default=1, verbose_name='测试序号'),
        ),
        migrations.AddField(
            model_name='testtype',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
            preserve_default=False,
        ),
    ]
