# Generated by Django 2.1.2 on 2019-04-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20190401_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testtype',
            options={'ordering': ('index',), 'verbose_name_plural': '测试类型分类'},
        ),
        migrations.AddField(
            model_name='testtype',
            name='is_test',
            field=models.BooleanField(default=True, verbose_name='是否测试'),
        ),
    ]
