# Generated by Django 2.1.2 on 2019-04-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20190401_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtype',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改'),
        ),
    ]
