# Generated by Django 2.1.2 on 2019-04-01 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20190401_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webcase',
            name='oprateOBj',
        ),
    ]
