# Generated by Django 2.1.2 on 2019-04-01 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_remove_webcase_oprateobj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcase',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最近修改'),
        ),
        migrations.AlterField(
            model_name='webcase',
            name='webManager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.TestType', verbose_name='测试分类'),
        ),
    ]
