# Generated by Django 2.1.2 on 2019-04-01 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_auto_20190401_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webcase',
            old_name='webManager',
            new_name='testtype',
        ),
    ]
