# Generated by Django 2.1.2 on 2019-04-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_auto_20190401_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcase',
            name='webcss',
            field=models.TextField(blank=True, max_length=800, null=True, verbose_name='Css选择器'),
        ),
        migrations.AlterField(
            model_name='webcase',
            name='webname',
            field=models.CharField(default=1, max_length=100, verbose_name='步骤名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='webcase',
            name='weboprate',
            field=models.TextField(blank=True, max_length=800, null=True, verbose_name='元素操作'),
        ),
        migrations.AlterField(
            model_name='webcase',
            name='webparam',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='操作参数'),
        ),
    ]
