# Generated by Django 2.1.2 on 2019-04-01 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_auto_20190401_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webcase',
            old_name='testtype',
            new_name='testType',
        ),
    ]
