# Generated by Django 2.1.2 on 2019-04-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_checkwebcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkwebcase',
            name='checktext',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='验证数据'),
        ),
        migrations.AlterField(
            model_name='checkwebcase',
            name='webparam',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='操作参数'),
        ),
    ]
