# Generated by Django 2.1.2 on 2019-04-03 11:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('user', '0032_auto_20190401_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_all', models.IntegerField(default=0)),
                ('test_pass', models.IntegerField(default=0)),
                ('test_fail', models.IntegerField(default=0)),
                ('test_time', models.DateField(default=django.utils.timezone.now)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '测试计数',
                'verbose_name_plural': '测试计数',
                'ordering': ['-test_time'],
            },
        ),
    ]
