# Generated by Django 2.1.2 on 2019-04-03 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_testrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apicase',
            name='apiManager',
        ),
        migrations.RemoveField(
            model_name='apicase',
            name='apistatus',
        ),
        migrations.AddField(
            model_name='apicase',
            name='result',
            field=models.BooleanField(default=False, verbose_name='是否通过'),
        ),
        migrations.AddField(
            model_name='apicase',
            name='testType',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to='user.TestType', verbose_name='测试分类'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apicase',
            name='apijson',
            field=models.TextField(blank=True, max_length=800, null=True, verbose_name='请求数据json'),
        ),
        migrations.AlterField(
            model_name='apicase',
            name='apimethod',
            field=models.CharField(blank=True, choices=[('get', 'get'), ('post', 'post'), ('put', 'put'), ('delete', 'delete'), ('patch', 'patch')], default='get', max_length=200, null=True, verbose_name='请求方法'),
        ),
        migrations.AlterField(
            model_name='apicase',
            name='apiname',
            field=models.CharField(default=1, max_length=100, verbose_name='接口名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apicase',
            name='apiparam',
            field=models.TextField(blank=True, max_length=800, null=True, verbose_name='请求参数param'),
        ),
        migrations.AlterField(
            model_name='apicase',
            name='apiresponse',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='响应数据json'),
        ),
        migrations.AlterField(
            model_name='apicase',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
