# Generated by Django 2.1.2 on 2019-04-03 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_apicase_apiname1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apicase',
            name='apiname1',
        ),
    ]
