# Generated by Django 2.1.2 on 2019-04-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_remove_apicase_apiname1'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicase',
            name='testdata',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='测试数据'),
        ),
    ]
