# Generated by Django 2.1.2 on 2019-04-03 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_auto_20190403_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apicase',
            options={'ordering': ['index'], 'verbose_name_plural': '后端测试案例'},
        ),
    ]
