# Generated by Django 2.1.2 on 2019-04-03 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_auto_20190403_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apicase',
            options={'ordering': ['-index'], 'verbose_name_plural': '后端测试案例'},
        ),
    ]
