# Generated by Django 2.1.2 on 2019-04-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_auto_20190404_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webmanager',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改'),
        ),
    ]
