# Generated by Django 2.1.2 on 2019-04-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_auto_20190406_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='apiresult',
            field=models.BooleanField(default=False, verbose_name='后端测试结果'),
        ),
        migrations.AddField(
            model_name='project',
            name='result',
            field=models.BooleanField(default=False, verbose_name='测试结果'),
        ),
        migrations.AddField(
            model_name='project',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改'),
        ),
        migrations.AddField(
            model_name='project',
            name='webresult',
            field=models.BooleanField(default=False, verbose_name='前端测试结果'),
        ),
    ]
