# Generated by Django 2.1.2 on 2019-05-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_auto_20190406_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apimanager',
            options={'ordering': ['-update_time'], 'verbose_name_plural': '后端测试管理'},
        ),
        migrations.AlterModelOptions(
            name='webmanager',
            options={'ordering': ['-update_time'], 'verbose_name_plural': '前端测试管理'},
        ),
        migrations.AddField(
            model_name='apicase',
            name='contentType',
            field=models.TextField(default='application/json', max_length=800, verbose_name='请求body格式'),
        ),
        migrations.AlterField(
            model_name='apimanager',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改'),
        ),
    ]
