# Generated by Django 2.1.2 on 2019-05-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_auto_20190522_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicase',
            name='actions',
            field=models.TextField(blank=True, max_length=800, null=True, verbose_name='权限定义的动作集合'),
        ),
        migrations.AddField(
            model_name='apicase',
            name='isAdmin',
            field=models.BooleanField(default=False, verbose_name='测试是否需要管理员权限'),
        ),
        migrations.AddField(
            model_name='apicase',
            name='isAuth',
            field=models.BooleanField(default=False, verbose_name='测试是否需要授权'),
        ),
        migrations.AddField(
            model_name='apicase',
            name='objectId',
            field=models.TextField(blank=True, max_length=800, null=True, verbose_name='权限针对的对象-id'),
        ),
        migrations.AddField(
            model_name='apicase',
            name='objectType',
            field=models.TextField(blank=True, max_length=800, null=True, verbose_name='权限针对的对象-type'),
        ),
        migrations.AddField(
            model_name='apicase',
            name='operatorId',
            field=models.TextField(blank=True, max_length=800, null=True, verbose_name='权限将要赋予的对象-id'),
        ),
        migrations.AddField(
            model_name='apicase',
            name='operatorType',
            field=models.TextField(blank=True, max_length=800, null=True, verbose_name='权限将要赋予的对象-Type'),
        ),
    ]
