# Generated by Django 2.1.2 on 2019-05-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_auto_20190522_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='adminPsw',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='管理员密码'),
        ),
        migrations.AddField(
            model_name='project',
            name='adminUser',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='管理员账户'),
        ),
        migrations.AddField(
            model_name='project',
            name='testPsw',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='测试密码'),
        ),
        migrations.AddField(
            model_name='project',
            name='testUser',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='测试账户'),
        ),
    ]
