# Generated by Django 2.1.2 on 2019-06-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0049_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpcloud', models.CharField(max_length=200, verbose_name='云平台')),
                ('currentplate', models.CharField(max_length=200, verbose_name='电流表')),
                ('offLineKey', models.CharField(max_length=200, verbose_name='离线Key工具')),
                ('syncAgent', models.CharField(max_length=200, verbose_name='syncAgent')),
                ('transferStation', models.CharField(max_length=200, verbose_name='TransferStation')),
            ],
        ),
    ]
