# Generated by Django 2.1.2 on 2019-06-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0051_auto_20190603_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpversion',
            name='releaseNote',
            field=models.CharField(default=1, max_length=800, verbose_name='Release Note'),
            preserve_default=False,
        ),
    ]
