# Generated by Django 2.1.2 on 2019-06-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0053_report_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='version',
            field=models.CharField(max_length=800, verbose_name='软件版本信息'),
        ),
    ]
