# Generated by Django 2.1.2 on 2019-06-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0054_auto_20190603_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='releaseNote',
            field=models.CharField(default=1, max_length=800, verbose_name='Release Note'),
            preserve_default=False,
        ),
    ]
