# Generated by Django 2.1.2 on 2019-06-03 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0055_report_releasenote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MpVersion',
        ),
    ]
