# Generated by Django 2.1.2 on 2019-06-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0056_delete_mpversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='all',
            field=models.CharField(default=1, max_length=800, verbose_name='所有信息'),
            preserve_default=False,
        ),
    ]
