# Generated by Django 2.1.2 on 2019-06-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0057_report_all'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='all',
            new_name='allInfo',
        ),
    ]
