# Generated by Django 2.1.2 on 2019-06-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0058_auto_20190604_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='allInfo',
            field=models.CharField(max_length=10000, verbose_name='所有信息'),
        ),
    ]
