# Generated by Django 2.1.2 on 2019-06-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0059_auto_20190604_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='allInfo',
            field=models.TextField(verbose_name='所有信息'),
        ),
    ]
