# Generated by Django 2.1 on 2019-08-09 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0061_report_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiVar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varname', models.CharField(max_length=100, verbose_name='变量名称')),
                ('varvalue', models.CharField(max_length=800, verbose_name='变量值')),
                ('testType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.TestType', verbose_name='测试分类')),
            ],
            options={
                'verbose_name_plural': '后端自定义变量',
            },
        ),
    ]
