# Generated by Django 2.1 on 2019-08-09 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0062_apivar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apivar',
            name='testType',
        ),
        migrations.AddField(
            model_name='apivar',
            name='apiManager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.ApiManager', verbose_name='后端模块'),
            preserve_default=False,
        ),
    ]
