# Generated by Django 2.1 on 2019-08-14 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0063_auto_20190809_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(max_length=20, null=True, verbose_name='app测试名称')),
                ('appdes', models.CharField(max_length=50, null=True, verbose_name='app测试描述')),
                ('desired_caps', models.TextField(blank=True, max_length=800, null=True, verbose_name='desired_caps参数')),
                ('result', models.BooleanField(default=False, verbose_name='测试结果')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后修改')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Project', verbose_name='所属项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name_plural': 'app测试管理',
                'ordering': ['-update_time'],
            },
        ),
    ]
