# Generated by Django 2.1 on 2019-08-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0064_appmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='appresult',
            field=models.BooleanField(default=False, verbose_name='后端测试结果'),
        ),
        migrations.AlterField(
            model_name='appmanager',
            name='appdes',
            field=models.CharField(max_length=50, null=True, verbose_name='app描述'),
        ),
        migrations.AlterField(
            model_name='appmanager',
            name='appname',
            field=models.CharField(max_length=20, null=True, verbose_name='app名称'),
        ),
    ]
