# Generated by Django 2.1 on 2019-08-14 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0065_auto_20190814_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(max_length=100, verbose_name='步骤名称')),
                ('selectmethod', models.TextField(blank=True, max_length=800, null=True, verbose_name='元素定位方法')),
                ('selectparam', models.TextField(blank=True, max_length=800, null=True, verbose_name='元素定位参数')),
                ('appoprate', models.TextField(blank=True, max_length=800, null=True, verbose_name='元素操作')),
                ('appparam', models.TextField(blank=True, max_length=500, null=True, verbose_name='操作参数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最近修改')),
                ('index', models.IntegerField(default=1, verbose_name='测试序号')),
                ('testType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.TestType', verbose_name='测试分类')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name_plural': 'app测试案例',
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='CheckAppCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(max_length=100, verbose_name='步骤名称')),
                ('selectmethod', models.TextField(blank=True, max_length=800, null=True, verbose_name='元素定位方法')),
                ('selectparam', models.TextField(blank=True, max_length=800, null=True, verbose_name='元素定位参数')),
                ('appoprate', models.TextField(blank=True, max_length=800, null=True, verbose_name='元素操作')),
                ('appparam', models.TextField(blank=True, max_length=500, null=True, verbose_name='操作参数')),
                ('checktext', models.TextField(blank=True, max_length=500, null=True, verbose_name='验证数据')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最近修改')),
                ('index', models.IntegerField(default=1, verbose_name='测试序号')),
                ('testType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.TestType', verbose_name='测试分类')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name_plural': 'app测试数据验证',
                'ordering': ('index',),
            },
        ),
        migrations.AlterField(
            model_name='appmanager',
            name='desired_caps',
            field=models.TextField(blank=True, default='', max_length=800, null=True, verbose_name='desired_caps参数'),
        ),
    ]
