# Generated by Django 2.1 on 2019-08-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0066_auto_20190814_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcase',
            name='appoprate',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='元素操作'),
        ),
        migrations.AlterField(
            model_name='appcase',
            name='appparam',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='操作参数'),
        ),
        migrations.AlterField(
            model_name='appcase',
            name='selectmethod',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='元素定位方法'),
        ),
        migrations.AlterField(
            model_name='appcase',
            name='selectparam',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='元素定位参数'),
        ),
        migrations.AlterField(
            model_name='checkappcase',
            name='appoprate',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='元素操作'),
        ),
        migrations.AlterField(
            model_name='checkappcase',
            name='appparam',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='操作参数'),
        ),
        migrations.AlterField(
            model_name='checkappcase',
            name='checktext',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='验证数据'),
        ),
        migrations.AlterField(
            model_name='checkappcase',
            name='selectmethod',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='元素定位方法'),
        ),
        migrations.AlterField(
            model_name='checkappcase',
            name='selectparam',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='元素定位参数'),
        ),
    ]
