# Generated by Django 2.1 on 2019-09-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0069_appsrccase_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsrccase',
            name='srcname',
            field=models.CharField(max_length=100, null=True, verbose_name='测试脚本'),
        ),
    ]
